### ISSUE TITLE
inconsistant redux-form creation?

### ISSUE THREAD

**Issue by m4v15** [fac-12/peppr#40]
[Here](https://github.com/fac-12/peppr/blob/master/client/src/components/addrecipe/NewRecipeForm.js#L85-L94) you create and export the redux form in one way, whilst [here](https://github.com/fac-12/peppr/blob/master/client/src/components/addrecipe/UrlForm.js#L73-L76)(and everywhere else I think) you do it another way. The second one looks better to me, but yeah just flagging it.

**Comment by hannahcmtucker** [comment]
done :)
