### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by m4v15** [fac-12/peppr#43]
At the moment, if someone tries to sign in with the wrong password or email, they'll get an error telling them it's wrong 👍 . However, if they try to sign in with _correct_ username and password, but for some reason your database is down for example, they'll get the same error message. You might wanna think about analysing [the error sent back](https://github.com/fac-12/peppr/blob/master/client/src/actions/auth.js#L49-L50) maybe have a reducer which sends a different error message depending on the status code or something.

**Comment by m4v15** [comment]
Other smaller things:

- you call it `err` [here](https://github.com/fac-12/peppr/blob/master/client/src/actions/auth.js#L15) but `error` [here](https://github.com/fac-12/peppr/blob/master/client/src/actions/auth.js#L49)
- your using `authError` as a way of [generating a non-auth error message](https://github.com/fac-12/peppr/blob/master/client/src/actions/recipes.js#L16) so maybe this is a bad name/set up.

**Comment by hannahcmtucker** [comment]
#51

**Comment by hannahcmtucker** [comment]
done :)
