### ISSUE TITLE
Add Recipe bug

### ISSUE THREAD

**Issue by jamiecoe** [fac-12/peppr#67]
Potential bug when user scrapes a URL, then edits a detail and saves. The saved version potentially not coming through because of `enableReinitialize` in `NewRecipeForm.js`:
```
NewRecipeForm = reduxForm({
  validate,
  enableReinitialize: true,
  form: "NewRecipeForm",
})(NewRecipeForm);
```

Needs investigating!

**Comment by hannahcmtucker** [comment]
this works OK in my testing :)
